<?php require __dir__."/../layout/app.phtml"?>

<div class="container">
<div class="col-md-5">
    <div class="panel panel-default">
    <div class="panel-heading">
        <strong>Seznam knih</strong>
        <span class="pull-right"><a href="<?=$router->pathFor('lists-edit');?>"><span class="glyphicon glyphicon-plus"></span> Přidat knihu</a></span>
    </div>
    <div class="panel-body">
    <?php if (is_array($books) && count($books)):?>
        <ul class='list-group'>
        <?php foreach($books as $book):?>
        <li class='list-group-item'>
            <?=$book['author'] == ""?"":$book['author'] . ": "?><?=$book['name']?>
            <a href="#" class='btn btn-xs btn-danger pull-right'>Odstranit</a>
        </li>
        <?php endforeach;?>
        </ul>
    <?php else:?>
        <span class='text-muted'>Žádné knihy nenalezeny</span>
    <?php endif?>
    </div>
    </div>
</div>

<div class="col-md-5 col-md-offset-2">
    <div class="panel panel-default">
    <div class="panel-heading">
        <strong>Nahrát nový kánon (Stávající bude přepsán)</strong>
    </div>
    <div class="panel-body">
    <p>
    očekávaný formát csv souboru je:<br />
    <pre>[id];[region id];[author];[name];[genere id]</pre>
    </p>
    <form method="post" enctype="multipart/form-data" action="<?=$router->pathFor('admin-upload')?>">
        <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
        <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
        <input type="file" name="example1"/><br />
        <input type="submit"/>
    </form>
    </div>
    </div>
</div>

