<h3>Dashboard <small>admin</small></h3>
<?php if (substr($config['version'], 6) == 'dev'):?>
    <p class="bg-danger">&nbsp;<span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span> Používáte <b>DEV</b> verzi programu, která může být místy nestabilní a zobrazuje veškerá upozornění.</p>
<?php endif;?>
<hr />
<p>Vítejte v aplikaci Studijní Platforma.<br />
Tento systém Vám umožňuje přístup k nejrůznějším službám, které Vaše škola vyžaduje.</p>
