<h3>Dashboard <small>Student</small></h3>
<hr />
<p>Vítejte v aplikaci Studijní Platforma.<br />
Tento systém Vám umožňuje přístup k nejrůznějším službám, které Vaše škola vyžaduje.</p>
<hr>
<h4>Poznámka</h4>
<p>
    Aplikace je stále v aktivním vývoji a letošní rok je celý systém v testovacím provozu.<br /><br />
    Pokud v aplikaci najdete chybu, nebo Vás napadlo rozšíření systému, neváhejte a otevřete nový <a href="https://github.com/keombre/sup/issues" target="_blank">Issue</a>.
    <br />Neočekávejte ale prosím, že na Vaši žádost/připomínku budu reagovat ihned. Nemám bohužel moc volného času, který bych mohl vývoji SUPa věnovat.
</p>