<?php require __dir__."/../layout/app.phtml"?>

Schválit kánon:
<form class="form-horizontal" method="post" action="">
    <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
    <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
    <div class="form-group">
        <label class="col-md-4 control-label" for="id">Číslo kánonu:</label>
        <div class="col-md-6">
            <input class="form-control" type="number" min=10000 max=99999 name="id" id="id" required autofocus>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-8 col-md-offset-4">
            <input class="btn btn-primary" type="submit" value="Schválit">
        </div>
    </div>
</form>

Díla:<br />
<?php
    if (is_array(@$books)) {
        echo "<table>";
        echo "<tr><td>Autor</td><td>Dílo</td><td>Počet</td></tr>";
        foreach($books as $book) {
            echo "<tr><td>$book[0]</td><td>$book[1]</td><td>$book[2]</td></tr>" . PHP_EOL;
        }
        echo "</table>";
    } else {
        echo "Nikdo si nevybral žádné knihy."; 
    }
?>

Seznam schválených kánonů:<br />
<?php
    if (is_array(@$lists)) {
        echo "<table>";
        echo "<tr><td>ID</td><td>Jméno</td><td>Třída</td></tr>";
        foreach($lists as $list) {
            echo "<tr><td><a href='".$router->pathFor("lists", ["id" => $list['id']])."'>$list[id]</a></td><td>$list[name]</td><td>$list[class]</td></tr>" . PHP_EOL;
        }
        echo "</table>";
    } else {
        echo "Žádné schválení kánony";
    }
?>