<?php require __dir__ . "/../layout/app.phtml"?>

<div class="container main">
	<div class="col-md-6">
		<form id="form-add" method="post">
		<input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
		<input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
		<input type="hidden" name="_METHOD" value="PUT" />
		<div class="form-group">
			<label for="books[]">Školní kánon:</label>
			<input id="search" class="form-control" placeholder="Vyhledávejte" autofocus />
			<br />
			<select name="books[]" id="books" multiple="multiple" class="form-control" size="25" ondblclick="send('add')">
			<?php foreach($books as $rid => $book):?>
				<optgroup label='<?=array_key_exists($rid, $regions)?$regions[$rid]:"Oblast č. ". $rid?>'>
				<?php foreach($book as $id => $info):?>
					<option value='<?=$id?>'><?=$info['author'] == ''?"":$info['author'] . ": "?><?=$info['name']?><?=array_key_exists($info['genere'], $generes)?"(".$generes[$info['genere']].")":""?></option>
				<?php endforeach;?>
				</optgroup>
				<?php endforeach;?>
			</select>
		</div>
		</form>
	</div>
	<div class="col-md-2">
		<div class="my-buttons">
			<button class="form-control btn btn-default" onclick="send_add()">
				Přidat <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
			</button>
			<button class="form-control btn btn-default" onclick="send_del()">
				<span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span> Odebrat
			</button>
			<button class="form-control btn btn-danger" data-toggle="modal" data-target="#clearModal" onclick="return false;">
				<span class="glyphicon glyphicon-ban-circle" aria-hidden="true"></span> Smazat kánon
			</button>
		</div>
	</div>
	<div class="col-md-4">
		<form id="form-del" method="post">
		<input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
		<input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
		<input type="hidden" name="_METHOD" value="DELETE" />
		<div class="form-group">
			<label for="books[]">Můj kánon: (<?=$listLength?>/20)</label>
			<select name="books[]" id="myBooks" multiple="multiple" class="form-control" size="26" ondblclick="send('remove')">
			<?php foreach($list as $rid => $book):?>
				<optgroup label='<?=array_key_exists($rid, $regions)?$regions[$rid]:"Oblast č. ". $rid?>'>
				<?php foreach($book as $id => $info):?>
				<option value='<?=$id?>'><?=$info['author'] == ''?"":$info['author'] . ": "?><?=$info['name']?><?=array_key_exists($info['genere'], $generes)?"(".$generes[$info['genere']].")":""?></option>
				<?php endforeach;?>
				</optgroup>
			<?php endforeach;?>
			</select>
			<br />
		</div>
		</form>
		<button class="form-control btn btn-success" onclick="send('finish')">
			Dokončit kánon <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
		</button>
	</div>
</div>
</div>
<div id="clearModal" class="modal fade" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4 class="modal-title">Opravdu chcete kánon vyčistit?</h4>
		</div>
		<div class="modal-body">
			<p>
				Tato akce je nevratná. Celý kánon budete muset vytvořit znovu.<br />
				Kánon, který jste již odeslali, nebude nijak ovlivněn.
			</p>
		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-danger pull-left" onclick="send_wipe()">Chápu riziko, odstraň kánon!</button>
			<button type="button" class="btn btn-default" data-dismiss="modal">Zrušit</button>
		</div>
	</div>
</div>
</div>
<script>
function send_add() {
	$('#form-add').submit()
}
function send_del() {
	$('#form-del').submit()
}
function send_wipe() {
	$('#myBooks option').prop('selected', true);
	$('#form-del').submit()
}
</script>