<div class="panel panel-default">
    <div class="panel-body">
        <p>Kánon zkontrolujte, odešlete a poté vytiskněte.</p>
        <?php if ($print):?>
        <a class="btn btn-default" href="<?=$router->pathFor('lists')?>">Zpět</a>
        <div class="pull-right btn-group">
            <button class="btn btn-success disabled" data-toggle="tooltip" data-placement="top" title="Kánon již byl odeslán">Odeslat</button>
            <button class="btn btn-primary" onclick="window.print()">Tisk</button>
        </div>
        <?php else:?>
        <a class="btn btn-default" href="<?=$router->pathFor('lists-edit', ["id" => $listID])?>">Zpět</a>
        <div class="pull-right">
            <form method="post">
                <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
                <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
                <input type="hidden" name="_METHOD" value="PUT" />
                <div class="btn-group">
                    <button class="btn btn-success">Odeslat</button>
                    <button class="btn btn-primary disabled" data-toggle="tooltip" data-placement="top" title="Před tiskem kánon odešlete">Tisk</button>
                </div>
            </form>
        </div>
        <?php endif?>
    </div>
</div>
<div class="print">
<div class="only-print">
<h3>Kánon <?=date("Y")?></h3>
<table>
    <tr>
        <td>Jméno:&nbsp;&nbsp;</td>
        <td><strong><?=$auth->user->getAttrib('surname')?></strong></td>
    </tr>
    <tr>
        <td>Třída: </td>
        <td><strong><?=$auth->user->getAttrib('class')?></strong></td>
    </tr>
</table>
<hr>
</div>
<h4>Knihy</h4>
<table class="table table-hover table-condensed">
    <thead>
        <tr>
            <th class="col-md-2">Autor</th>
            <th class="col-md-4">Dílo</th>
        </tr>
    </thead>
    <?php foreach($list as $book):?>
    <tr>
        <td><?=$book['author']?></td>
        <td><?=$book['name']?></td>
    </tr>
    <?php endforeach;?>
</table>
</div>
</div>