<?php require __dir__ . "/../layout/app.phtml"?>

<div class="container">
<div class="col-md-6 col-md-offset-3">
<div class="panel panel-default">
    <div class="panel-heading">Vaše evidenční číslo: <b><?=$id?></b></div>
    <div class="panel-body">
        <span>
            Pokud zde uvedete chybné údaje, váš profil nebude brán v potaz.
        </span>
        <form class="form-horizontal" method="post" action="<?=$router->pathFor('register-s2')?>">
            <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
            <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
            <div class="form-group">
                <label class="col-md-4 control-label" for="givenname">Jméno:</label>
                <div class="col-md-6">
                    <input class="form-control" type="text" name="givenname" required autofocus>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-4 control-label" for="surname">Příjmení:</label>
                <div class="col-md-6">
                    <input class="form-control" type="text" name="surname" required>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-4 control-label" for="class">Třída:</label>
                <div class="col-md-6">
                    <select class="form-control" name="class" id="class" required>
                        <option disabled selected value="">Zvolte třídu</option>
                        <option value="A">VIII. A</option>
                        <option value="B">VIII. B</option>
                        <option value="C">4. C</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-8 col-md-offset-4">
                    <input class="btn btn-primary" type="submit" value="Pokračovat">
                </div>
            </div>
        </form>
    </div>
    </div>
</div>
</div>
</div>
<?php require __dir__ . "/../layout/footer.phtml"?>