<?php require __dir__."/../layout/app.phtml"?>

<div class="container">
<h3><?=$lang->g('title', 'modules');?></h3>
<hr />
<div class="col-md-6">
    <div class="panel panel-default">
    <div class="panel-heading"><strong><?=$lang->g('installed-title', 'modules');?></strong></div>
    <div class="panel-body">
    <?php if (is_array($local) && count($local)):?>
        <ul class='list-group'>
        <?php foreach($local as $entry):?>
        <li class="list-group-item">
        <b><?=$entry->getName()?></b> v<?=$entry->getVersion()?>
        <span onclick="manage('<?=$entry->getName()?>', '<?=$entry->isEnabled()?'DELETE':'PUT'?>')">
            &nbsp;<input type="checkbox" <?=$entry->isEnabled()?'checked':''?> name="edit" data-size="mini" data-on="<?=$lang->g('installed-enabled', 'modules');?>" data-off="<?=$lang->g('installed-disabled', 'modules');?>" data-onstyle="success" data-offstyle="danger" data-toggle="toggle">
        </span>
        <button onclick="send('<?=$entry->getName()?>', 'DELETE')" class='btn btn-xs pull-right btn-danger'><?=$lang->g('installed-remove', 'modules');?></button>
        <?php if ($entry->getUpdate()):?>
            <div class="pull-right">
                <button onclick="send('<?=$entry->getName()?>', 'PATCH')" class='btn btn-xs btn-success'><?=$lang->g('installed-update', 'modules');?></button>&nbsp;
            </div>
        <?php endif;?>
        <?php if (array_key_exists('description', $entry->getManifest())):?>
            <br /><small><?=$entry->getManifest()['description']?></small>
        <?php endif;?>
        </li>
        <?php endforeach;?>
        </ul>
    <?php else:?>
        <span class='text-muted'><?=$lang->g('installed-notfound', 'modules');?></span>
    <?php endif?>
    </div>
    </div>
</div>
<div class="col-md-6">
    <div class="panel panel-default">
    <div class="panel-heading">
        <strong><?=$lang->g('remote-title', 'modules');?></strong>
    </div>
    <div class="panel-body">
    <?php if (is_array($remote) && count($remote)):?>
        <ul class='list-group'>
        <?php foreach($remote as $entry):?>
        <?php if (version_compare(substr($config['version'], 0, 5), $entry->getBaseVersion(), ">=")):?>
            <li class="list-group-item"><b><?=$entry->getName()?></b> v<?=$entry->getVersion()?>
                <button onclick="send('<?=$entry->getName()?>', 'PUT')" class='btn btn-xs pull-right btn-success'><?=$lang->g('remote-install', 'modules');?></button>
            <?php if (array_key_exists('description', $entry->getManifest())):?>
                <br /><small><?=$entry->getManifest()['description']?></small>
            <?php endif;?>
            </li>
        <?php else:?>
            <li class="list-group-item disabled">
                <b><?=$entry->getName()?></b> v<?=$entry->getVersion()?>
                <span class="pull-right"><?=$lang->g('remote-minVersion', 'modules');?> <b>v<?=$entry->getBaseVersion()?></b></span>
            <?php if (array_key_exists('description', $entry->getManifest())):?>
                <br /><small><?=$entry->getManifest()['description']?></small>
            <?php endif;?>
            </li>
        <?php endif;?>
        <?php endforeach;?>
        </ul>
    <?php else:?>
        <span class='text-muted'><?=$lang->g('remote-notfound', 'modules');?></span>
    <?php endif?>
    </div>
    </div>
    </div>
<form method="post" action="<?=$router->pathFor('modules-install')?>">
    <input type="hidden" name="_METHOD" id="method" />
    <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
    <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
    <input type="hidden" name="name" value="" id="name">
</form>
<form method="post" action="<?=$router->pathFor('modules-manage')?>">
    <input type="hidden" name="_METHOD" id="manage_method" />
    <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
    <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
    <input type="hidden" name="name" value="" id="manage_name">
</form>
</div>
<script>
function send(value, mode) {
    var elm = document.getElementById('name')
    elm.value = value
    document.getElementById('method').value = mode
    elm.parentNode.submit()
}
function manage(value, mode) {
    var elm = document.getElementById('manage_name')
    elm.value = value
    document.getElementById('manage_method').value = mode
    elm.parentNode.submit()
}
</script>

<?php require __dir__ . "/../layout/footer.phtml"?>