<?php require __dir__."/layout/app.phtml"?>

<div class="container">
<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#home">Domů</a></li>
  <li><a data-toggle="tab" href="#menu1">Přijímací řízení</a></li>
  <li><a data-toggle="tab" href="#menu2">Volitelné předměty</a></li>
  <li><a data-toggle="tab" href="#menu3">Maturitní kánon</a></li>
</ul>
<div class="panel panel-default" style="border-top: none;border-top-left-radius: 0;border-top-right-radius: 0;">
<div class="tab-content panel-body">
  <div id="home" class="tab-pane fade in active">
    <?=$home?>
  </div>
  <div id="menu1" class="tab-pane fade">
    <?=$admissions?>
  </div>
  <div id="menu2" class="tab-pane fade">
    <?=$subjects?>
  </div>
  <div id="menu3" class="tab-pane fade">
    <?=$lists?>
  </div>
</div>
</div>
</div>
<?php require __dir__ . "/layout/footer.phtml"?>