<?php require __dir__."/layout/app.phtml"?>

<div class="container">
<div class="col-md-6 col-md-offset-3">
<div class="panel panel-default">
    <div class="panel-heading"><a href="<?=$router->pathFor('register-s1')?>">Nový uživatel</a></div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">Stávající uživatel</div>
    <div class="panel-body">
        <form class="form-horizontal" method="post" action="<?=$router->pathFor('login')?>">
            <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
            <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
            <div class="form-group">
                <label class="col-md-4 control-label" for="name">Přihlašovací kód:</label>
                <div class="col-md-6">
                    <input class="form-control" type="text" name="name" id="name" required autofocus>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-4 control-label" for="pass">Heslo:</label>
                <div class="col-md-6">
                    <input class="form-control" type="password" name="pass" id="pass" required>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-8 col-md-offset-4">
                    <input class="btn btn-primary" type="submit" value="Přihlásit se">
                </div>
            </div>
        </form>
    </div>
    </div>
</div>
</div>
</div>