<?php require __dir__."/layout/app.phtml"?>

<div class="container">
<div class="col-md-6 col-md-offset-3">
<div class="panel panel-default">
    <div class="panel-heading"><a href="<?=$router->pathFor('register-s1')?>"><?=$lang->g('new-user', 'index')?></a></div>
</div>
<div class="panel panel-default">
    <div class="panel-heading"><?=$lang->g('existing-user', 'index')?></div>
    <div class="panel-body">
        <form class="form-horizontal" method="post" action="<?=$router->pathFor('login')?>">
            <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
            <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
            <div class="form-group">
                <label class="col-md-4 control-label" for="name"><?=$lang->g('username', 'index')?></label>
                <div class="col-md-6">
                    <input class="form-control" type="text" name="name" id="name" required autofocus>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-4 control-label" for="pass"><?=$lang->g('password', 'index')?></label>
                <div class="col-md-6">
                    <input class="form-control" type="password" name="pass" id="pass" required>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-8 col-md-offset-4">
                    <input class="btn btn-primary" type="submit" value="<?=$lang->g('login', 'index')?>">
                </div>
            </div>
        </form>
    </div>
    </div>
</div>
</div>
</div>
<img src="img/image.png" style="position: fixed; right: -50px; bottom: 15px; z-index: -1; width: 500px; opacity: 0.6;"/>
<?php require __dir__ . "/layout/footer.phtml"?>