<?php require __dir__."/layout/app.phtml"?>

<script src="<?=$ROOT_PATH?>/js/background.js"></script>
<script>
particlesJS.load('particles-js', '<?=$ROOT_PATH?>/js/background.json');
</script>

<style>
#particles-js {
    position: absolute;
    top: -10px;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: -1;
}
.panel {
    margin-top: 60px;
}
</style>

<div class="container">
<div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
<div class="panel panel-default">
    <div class="panel-body">
        <h1 class="text-center"><?=$baseLang->g('title', 'main')?></h1>
        <h3 class="text-center" style="margin-bottom: 40px;"><?=$baseLang->g('existing-user', 'index')?></h3>
        <form class="form-horizontal" method="post" action="<?=$router->pathFor('login', [], ["next" => $next])?>">
            <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
            <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
            <div class="form-group">
                <label class="col-md-4 control-label" for="name"><?=$baseLang->g('username', 'index')?></label>
                <div class="col-md-6">
                    <input class="form-control" type="text" name="name" id="name" required autofocus>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-4 control-label" for="pass"><?=$baseLang->g('password', 'index')?></label>
                <div class="col-md-6">
                    <input class="form-control" type="password" name="pass" id="pass" required>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-8 col-md-offset-4">
                    <input class="btn btn-primary" type="submit" value="<?=$baseLang->g('login', 'index')?>">
                </div>
            </div>
        </form>
    </div>
    </div>
</div>
</div>
</div>
<div id="particles-js"></div>
<!--img src="img/image.png" style="position: fixed; right: -50px; bottom: 15px; z-index: -1; width: 500px; opacity: 0.6;"/-->
<?php require __dir__ . "/layout/footer.phtml"?>