<?php require __dir__."/layout/app.phtml"?>

<?php
if ($state == 0) {
    echo "Tento kánon není uzavřen.<br />";
} else if ($state == 1) {
    echo "Tento kánon je uzavřen a čeká na schválení.<br />";
} else if ($state == 2) {
    echo "Tento kánon je schválen.<br />";
}
?>
jméno: <?=$uname?><br />
třída: <?=$class?><br />

Díla:<br />
<?php
    if (is_array(@$books)) {
        echo "<table>";
        echo "<tr><td>Autor</td><td>Dílo</td><td>Období</td><td>Žánr</td></tr>";
        foreach($books as $book) {
            echo "<tr><td>$book[0]</td><td>$book[1]</td><td>$book[2]</td><td>$book[3]</td></tr>" . PHP_EOL;
        }
        echo "</table>";
    } else {
        echo "Kánon je prázdný."; 
    }
?>
<br />
<?php if ($state != 0):?>
<form method="post" class="form" action="<?=$router->pathFor('printer')?>">
    <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
    <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
    <input type="submit" value="Vytisknout">
</form>
<?php endif;?>