<?php require __dir__."/../layout/app.phtml"?>
<div class="container">
<div class="col-md-6 col-md-offset-3">
<div class="panel panel-default">
    <div class="panel-heading"><?=$lang->g('title', 'user-changePass')?></div>
    <div class="panel-body">
        <form class="form-horizontal" method="post">
            <input type="hidden" name="_METHOD" value="PUT" />
            <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
            <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
            <div class="form-group">
                <label class="col-md-4 control-label" for="old"><?=$lang->g('old', 'user-changePass')?></label>
                <div class="col-md-6">
                    <input class="form-control" type="password" name="old" id="old" required autofocus>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-4 control-label" for="pass"><?=$lang->g('new1', 'user-changePass')?></label>
                <div class="col-md-6">
                    <input class="form-control" type="password" name="pass" id="pass" required>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-4 control-label" for="pass2"><?=$lang->g('new2', 'user-changePass')?></label>
                <div class="col-md-6">
                    <input class="form-control" type="password" name="pass2" id="pass2" required>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-8 col-md-offset-4">
                    <input class="btn btn-primary" type="submit" value="<?=$lang->g('submit', 'user-changePass')?>">
                </div>
            </div>
        </form>
    </div>
    </div>
</div>
</div>
</div>
<?php require __dir__ . "/../layout/footer.phtml"?>