<?php require __dir__."/../layout/app.phtml"?>

<div class="container">
<div class="col-md-6">
    <div class="panel panel-default">
    <div class="panel-heading"><strong>Uživatelé</strong></div>
    <div class="panel-body">
    <?php if (is_array($users) && count($users)):?>
        <ul class='list-group'>
        <?php foreach($users as $user):?>
        <?php if (in_array(2, $user->getInfo('roles'))):?>
            <li class='list-group-item'><?=$user->getInfo('name')?></li>
        <?php else:?>
            <li class='list-group-item'><?=$user->getName()?> (<?=$user->getInfo('name')?>)
                <a href='#' onclick="let elm=document.getElementById('id');elm.value='<?=$user->getInfo('id')?>';elm.parentNode.submit()" class='btn btn-xs pull-right btn-danger'>Odstranit</a>
            </li>
        <?php endif;endforeach;?>
        </ul>
    <?php else:?>
        <span class='text-muted'>Žádní uživatelé</span>
    <?php endif?>
    </div>
    </div>
</div>
<div class="col-md-6">
    <div class="panel panel-default">
    <div class="panel-heading">
        <strong>Studenti</strong>
    </div>
    <div class="panel-body">
    <?php if (is_array(@$students) && count($students)):?>
        <ul class='list-group'>
        <?php foreach($students as $student):?>
            <li class='list-group-item'><a href='<?=$router->pathFor("lists-view", ["id" => $student->getInfo('id')])?>'><?=$student->getInfo('name')?></a> <?=$student->getName()?> <b><?=$student->getAttrib('class')?></b>
                <a href='#' onclick="let elm=document.getElementById('id');elm.value='<?=$student->getInfo('id')?>';elm.parentNode.submit()" class='btn btn-xs pull-right btn-danger'>Odstranit</a>
            </li>
        <?php endforeach;?>
        </ul>
    <?php else:?>
        <span class='text-muted'>Žádní studenti</span>
    <?php endif?>
    </div>
    </div>
    </div>
<form method="post" action="<?=$router->pathFor('user-manageUsers')?>">
    <input type="hidden" name="_METHOD" value="DELETE" />
    <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
    <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
    <input type="hidden" name="id" value="" id="id">
</form>
</div>
<?php require __dir__ . "/../layout/footer.phtml"?>