<?php require __dir__."/../layout/app.phtml"?>

<div class="container">
<h3>
<?=$baseLang->g('title', 'user-manage')?>
</h3>
<hr />
<div class="col-md-6">
    <div class="panel panel-default">
    <div class="panel-heading"><strong><?=$baseLang->g('users-title', 'user-manage')?></strong></div>
    <div class="panel-body">
    <?php if (is_array($users) && count($users)):?>
        <ul class='list-group'>
        <?php foreach($users as $user):?>
        <?php if ($user->getID() == 1):?>
            <li class='list-group-item'><?=$user->getUname()?></li>
        <?php else:?>
            <li class='list-group-item'><?=$user->getName()?> (<?=$user->getUname()?>)
                <i>
                <?php foreach ($user->getAttribute('roles') as $role):?>
                    <?php if ($user->getAttribute('activeRole') == $role):?>
                    <b><?=$baseLang->g($role, 'roles')?>&nbsp;</b>
                    <?php else:?>
                    <?=$baseLang->g($role, 'roles')?>&nbsp;
                    <?php endif;?>
                <?php endforeach;?>
                </i>
                <button onclick="let elm=document.getElementById('id');elm.value='<?=$user->getID()?>';elm.parentNode.submit()" class='btn btn-xs pull-right btn-danger'><?=$baseLang->g('users-remove', 'user-manage')?></button>
            </li>
        <?php endif;endforeach;?>
        </ul>
    <?php else:?>
        <span class='text-muted'><?=$baseLang->g('users-notfound', 'user-manage')?></span>
    <?php endif?>
    </div>
    </div>
</div>
<div class="col-md-6">
    <div class="panel panel-default">
    <div class="panel-heading">
        <strong><?=$baseLang->g('students-title', 'user-manage')?></strong>
    </div>
    <div class="panel-body">
    <?php if (is_array(@$students) && count($students)):?>
        <ul class='list-group'>
        <?php foreach($students as $student):?>
            <li class='list-group-item'><i><?=$student->getUname()?></i> <?=$student->getName()?> <b><?=$student->getAttribute('class')?></b>
                <button onclick="let elm=document.getElementById('id');elm.value='<?=$student->getID()?>';elm.parentNode.submit()" class='btn btn-xs pull-right btn-danger'><?=$baseLang->g('students-remove', 'user-manage')?></button>
            </li>
        <?php endforeach;?>
        </ul>
    <?php else:?>
        <span class='text-muted'><?=$baseLang->g('students-notfound', 'user-manage')?></span>
    <?php endif?>
    </div>
    </div>
    </div>
<form method="post" action="<?=$router->pathFor('user-manageUsers')?>">
    <input type="hidden" name="_METHOD" value="DELETE" />
    <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
    <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
    <input type="hidden" name="id" value="" id="id">
</form>
</div>
<?php require __dir__ . "/../layout/footer.phtml"?>