<footer class="footer no-print">
	<div class="container text-center">
		<hr>
		<small class="footer-small" ><strong><?=$lang->g('operator-label', 'footer')?></strong> <?=$lang->g('operator-text', 'footer')?>, <strong><?=$lang->g('developer', 'footer')?></strong> Jan Wijnhorst <a target="_blank" href="https://github.com/keombre">@keombre</a></small>
		<br />
		<small><?=$lang->g('sponsor', 'footer')?></small>
	</div>
	<small class="pull-right footer-version"><b>SUPi</b> <?=$lang->g('version', 'footer')?> 0.0.1</small>
</footer>
</body>
</html>