<footer class="footer">
	<div class="container text-center">
		<hr>
		<small class="footer-small" ><strong><?=$baseLang->g('operator-label', 'footer')?></strong> <?=$baseLang->g('operator-text', 'footer')?>, <strong><?=$baseLang->g('developer', 'footer')?></strong> Jan Wijnhorst <a target="_blank" href="https://github.com/keombre">@keombre</a></small>
		<br />
		<?php /*small><?=$baseLang->g('sponsor', 'footer')?></small*/?>
	</div>
	<small class="pull-right footer-version"><b>SUPi</b> <?=$baseLang->g('version', 'footer')?> <?=$config['version']?></small>
</footer>
</body>
</html>
