<footer class="footer no-print">
	<div class="container text-center">
		<hr>
		<small class="footer-small" ><strong>Správa:</strong> Ing. David Švarc, <strong>Aplikace:</strong> Jan Wijnhorst <a target="_blank" href="https://github.com/keombre">@keombre</a></small>
		<small>
			<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">
				<img alt="Licence Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/80x15.png" />
			</a>
			<br />Toto dílo podléhá licenci
			<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Uveďte původ-Neužívejte komerčně 4.0 Mezinárodní License</a>.
		</small>
	</div>
</footer>