<nav class="navbar navbar-default">
    <div class="container">
    <div class="navbar-header">
        <?php if ($auth->logged()):?>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only"><?=$baseLang->g('toggle-nav', 'main')?></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
        <?php endif?>
        <a class="navbar-brand" href="<?=$router->pathFor('dashboard')?>"><?=$baseLang->g('name', 'main')?></a>
    </div>
    <div id="navbar" class="collapse navbar-collapse text-center">
        <?php if (count($baseLang->getLangs())):?>
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#"><?=$baseLang->g('language', 'navbar')?>
            <span class="caret"></span></a>
                <ul class="dropdown-menu">
                <?php foreach ($baseLang->getLangs() as $lg => $name):?>
                <li><a href="<?=$router->pathFor('lang', ['lang' => $lg])?>"><?=$name?> (<?=$lg?>)</a></li>
                <?php endforeach;?>
                </ul>
            </li>
        </ul>
        <?php endif;?>
        <?php if ($auth->logged()):?>
        <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <span class="glyphicon glyphicon-user"></span>
            <span><b><?=$auth->getUser()->getName()?></b> (<?=$auth->getUser()->getAttribute('uname')?>)</span>
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li>
                    <a href="#" onclick="document.getElementById('logout').submit()">
                        <span class="glyphicon glyphicon-log-out"></span> <?=$baseLang->g('logout', 'navbar')?>
                    </a>
                </li>
                <li role="presentation" class="divider"></li>
                <?php /*<li><a href="<?=$router->pathFor('user-changePassword')?>"><span class="glyphicon glyphicon-lock"></span> <?=$baseLang->g('change-pass', 'navbar')?></a></li> */?>
                <li><a href="<?=$router->pathFor('user-changeRole')?>"><span class="glyphicon glyphicon-pencil"></span> <?=$baseLang->g('change-role', 'navbar')?></a></li>
                <?php if ($auth->getUser()->is(ROLE_ADMIN)):?>
                <li><a href="<?=$router->pathFor('user-manageUsers')?>"><span class="glyphicon glyphicon-briefcase"></span> <?=$baseLang->g('manage-users', 'navbar')?></a></li>
                <?php /*<li><a href="<?=$router->pathFor('user-register')?>"><span class="glyphicon glyphicon-plus"></span> <?=$baseLang->g('register-user', 'navbar')?></a></li> */?>
                <li role="presentation" class="divider"></li>
                <li><a href="<?=$router->pathFor('modules-view')?>"><span class="glyphicon glyphicon-cog"></span> <?=$baseLang->g('manage-modules', 'navbar')?></a></li>
                <?php endif;?>
            </ul>
        </li>
        </ul>
        <form action="<?=$router->pathFor('user-logout')?>" method="post" id="logout"></form>
        <?php endif?>
    </div>
    </div>
</nav>
