<nav class="navbar navbar-default">
    <div class="container">
    <div class="navbar-header">
        <?php if ($auth->logged()):?>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only"><?=$lang->g('toggle-nav', 'main')?></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
        <?php endif?>
        <a class="navbar-brand" href="<?=$router->pathFor('dashboard')?>"><?=$lang->g('name', 'main')?></a>
    </div>
    <div id="navbar" class="collapse navbar-collapse text-center">
        <?php if ($auth->logged()):?>
        <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <span class="glyphicon glyphicon-user"></span>
            <span><b><?=$auth->user['name']?></b> (<?=$auth->user['id']?>)</span>
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li>
                    <a href="#" onclick="document.getElementById('logout').submit()">
                        <span class="glyphicon glyphicon-log-out"></span> Odhlásit se
                    </a>
                </li>
                <li role="presentation" class="divider"></li>
                <li><a href="<?=$router->pathFor('changePassword')?>"><span class="glyphicon glyphicon-lock"></span> Změnit heslo</a></li>
                <?php if ($auth->user['level'] == 2):?>
                <li><a href="<?=$router->pathFor('manageUsers')?>"><span class="glyphicon glyphicon-briefcase"></span> Spravovat uživatele</a></li>
                <li><a href="<?=$router->pathFor('register')?>"><span class="glyphicon glyphicon-plus"></span> Registrovat učitele</a></li>
                <?php endif;?>
            </ul>
        </li>
        </ul>
        <form action="<?=$router->pathFor('logout')?>" method="post" id="logout"></form>
        <?php endif?>
        <li>
        <?php foreach ($lang->getLangs() as $lg => $name):?>
        <a href="<?=$router->pathFor('lang', ['lang' => $lg])?>"><?=$lg?></a> /
        <?php endforeach;?>
        </li>
    </div>
    </div>
</nav>