<?php require __dir__."/app.phtml"?>

<div class="container">
<ul class="nav nav-tabs">
    <li <?=$active == "home"?'class="active"':''?>><a href="<?=$router->pathFor('dashboard')?>"><?=$baseLang->g('home', 'dashboard')?></a></li>
    <?php foreach ($modules as $module):?>
    <li <?=$active == $module->getName()?'class="active"':''?>><a href="<?=$baseRouter->pathFor($module->getName())?>"><?=$module->getLocale('name', $baseLang->getActive())?></a></li>
    <?php endforeach;?>
</ul>
<div class="panel panel-default" style="border-top: none;border-top-left-radius: 0;border-top-right-radius: 0;">
<div class="panel-body">
    <?=$site?>
</div>
</div>
</div>
<?php require __dir__ . "/footer.phtml"?>